### ISSUE TITLE
CLI does not work in windows

### ISSUE THREAD

**Issue by Hellowlol** [idlesign/torrentool#6] opened 2016-09-21 14:09 UTC
It doesnt find the program.

**Comment by idlesign** [comment] 2016-09-22 11:59
What program?

**Comment by Hellowlol** [comment] 2016-09-22 17:58
torrent tool.

````
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. Med enerett.

C:\Users\user>pip install torrentool
Collecting torrentool
  Using cached torrentool-0.3.0-py2.py3-none-any.whl
Installing collected packages: torrentool
Successfully installed torrentool-0.3.0
C:\Users\user>torrentool torrent create /home/my/files_here/video.mkv
'torrentool' is not recognized as an internal or external command,
operable program or batch file.
````

**Comment by idlesign** [comment] 2016-12-26 14:21
Should now be handled by setuptools.

**Comment by idlesign** [comment] 2017-06-04 02:37
Closing this one. 
Feel free to reopen if the issue is relevant for the latest version.

**Closed by idlesign** 2017-06-04 02:37 UTC
Labels: enhancement
